version: '3.8'

services:
  # Flask app service
  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 8080
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: student
      MYSQL_HOST: mysql
    volumes:
      - .:/app
    command: flask run

  # MySQL service
  mysql:
    image: mysql:8.0
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: student
      MYSQL_HOST: mysql
