apiVersion : apps/v1
kind: Deployment
metadata:
  name: jordanxcloudlab 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jordanxcloudlab
  template:
    metadata:
      labels:
        app: jordanxcloudlab 
    spec:
      containers:
        - name: jordanxcloudlab 
          image: jmurraylab5registry.azurecr.io/jordanxcloudlab
          ports:
          - containerPort: 80